"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var userController_1 = require("../controllers/userController");
var router = express.Router();
router.post("/signup", userController_1.signUp);
router.post("/login", userController_1.Login);
router.delete("/delete/:id", userController_1.deleteAccount);
router.get("/:userName", userController_1.findUser);
exports.default = router;
